import hashlib
import os
from pathlib import Path

# Pastas tipicas para ignorar no walk (nao entram como relevantes)
IGNORAR_DIRS = {
    ".git",
    ".hg",
    ".svn",
    ".venv",
    "venv",
    "node_modules",
    "dist",
    "build",
    "out",
    "target",
    "bin",
    "obj",
    "__pycache__",
}


# Extensoes relevantes para documentacao tecnica profunda
EXT_RELEVANTES = {
    ".py",
    ".ipynb",
    ".sql",
    ".js",
    ".jsx",
    ".ts",
    ".tsx",
    ".java",
    ".go",
    ".c",
    ".h",
    ".cpp",
    ".hpp",
    ".cs",
    ".rb",
    ".php",
    ".rs",
    ".kt",
    ".kts",
    ".swift",
    ".html",
    ".css",
    ".scss",
    ".json",
    ".yml",
    ".yaml",
    ".toml",
    ".ini",
    ".xml",
    ".md",
    ".gradle",
    ".properties",
    ".sh",
    ".dockerfile",
    ".vue",
    ".mjs",
    ".cjs",
    ".mts",
    ".cts",
}


# Nomes de arquivos relevantes mesmo sem extensao
NOMES_RELEVANTES = {
    "Dockerfile",
    "Makefile",
    "README",
    "README.md",
    "LICENSE",
    "package.json",
    "package-lock.json",
    "yarn.lock",
    "pnpm-lock.yaml",
    "requirements.txt",
    "pyproject.toml",
    "poetry.lock",
    "Pipfile",
    "Pipfile.lock",
    "pom.xml",
    "build.gradle",
    "settings.gradle",
    "build.gradle.kts",
    "settings.gradle.kts",
}


# Extensoes tipicamente nao relevantes para documentacao tecnica profunda
EXT_IGNORAR = {
    ".png",
    ".jpg",
    ".jpeg",
    ".gif",
    ".webp",
    ".svg",
    ".ico",
    ".pdf",
    ".zip",
    ".tar",
    ".gz",
    ".rar",
    ".7z",
    ".jar",
    ".war",
    ".class",
    ".exe",
    ".dll",
    ".so",
    ".dylib",
    ".mp4",
    ".mp3",
    ".wav",
    ".avi",
    ".mov",
    ".woff",
    ".woff2",
    ".ttf",
    ".eot",
    ".csv",
    ".parquet",
    ".avro",
    ".orc",
    ".jsonl",
    ".ndjson",
    ".db",
    ".sqlite",
    ".pkl",
    ".joblib",
}


# Arquivos lock e afins para ignorar
NOMES_IGNORAR = {
    "LICENSE",
    "package-lock.json",
    "yarn.lock",
    "pnpm-lock.yaml",
    "poetry.lock",
    "Pipfile.lock",
    "composer.lock",
    "Cargo.lock",
    "go.sum",
}


DIRS_IGNORAR_POR_TRECHO = {
    ".pytest_cache",
    ".mypy_cache",
    ".ruff_cache",
    ".cache",
    "htmlcov",
    "generated",
    "gen",
    "autogen",
    ".idea",
    ".vscode",
}


ARQ_IGNORAR_POR_TRECHO = {
    ".coverage",
    "coverage.xml",
    "thumbs.db",
    ".ds_store",
}

AUTO_GERADO_MARCADORES = {
    "generated by",
    "do not edit",
    "autogenerated",
    "auto-generated",
    "@generated",
}


def _conteudo_indica_gerado(caminho: Path, size: int) -> bool:
    # Heuristica simples para arquivos gerados (comentarios com marcadores)
    try:
        # Para arquivos grandes, le apenas o inicio (onde marcadores costumam aparecer)
        if size > 1024 * 1024:
            with caminho.open("r", encoding="utf-8", errors="ignore") as f:
                texto = f.read(64 * 1024)
        else:
            texto = caminho.read_text(encoding="utf-8", errors="ignore")
    except Exception:
        return False
    linhas = texto.splitlines()
    for linha in linhas[:200]:
        s = linha.strip().lower()
        if not s:
            continue
        # So considera marcadores em comentarios
        if not (s.startswith("//") or s.startswith("/*") or s.startswith("*") or s.startswith("#") or s.startswith("--") or s.startswith(";")):
            continue
        for marcador in AUTO_GERADO_MARCADORES:
            if marcador in s:
                return True
    return False


def _indica_bundle(caminho: Path, size: int) -> bool:
    # Heuristica simples para bundles/minificados nao marcados
    if caminho.suffix.lower() not in {".js", ".css"}:
        return False
    try:
        if size > 300 * 1024:
            return True
        texto = caminho.read_text(encoding="utf-8", errors="ignore")
    except Exception:
        return False
    if "sourceMappingURL=" in texto:
        return True
    linhas = texto.splitlines()
    if not linhas:
        return False
    max_len = max(len(l) for l in linhas)
    if max_len > 300:
        return True
    return False


def _is_readme(nome: str) -> bool:
    # Detecta README com qualquer extensao/nome
    return "README" in nome.upper()


def _readme_rank(rel_path: str, size: int) -> tuple:
    # Ranking menor = melhor (preferencias globais)
    parts = rel_path.replace("\\", "/").split("/")
    depth = len(parts) - 1
    nome = parts[-1]
    root = depth == 0
    in_docs = len(parts) >= 2 and parts[0].lower() == "docs"
    nome_up = nome.upper()
    nome_low = nome.lower()
    prefer_pt = "pt" in nome_low or "br" in nome_low
    prefer_en = "en" in nome_low or "eng" in nome_low
    # Prioridade de idioma
    if prefer_pt:
        lang_rank = 0
    elif prefer_en:
        lang_rank = 1
    else:
        lang_rank = 2
    if root and nome_up == "README.MD":
        return (lang_rank, 0, depth, -size, nome.lower())
    if root and nome_up in {"README.RST", "README.TXT"}:
        return (lang_rank, 1, depth, -size, nome.lower())
    if root and _is_readme(nome):
        return (lang_rank, 2, depth, -size, nome.lower())
    if in_docs and _is_readme(nome):
        return (lang_rank, 3, depth, -size, nome.lower())
    return (lang_rank, 4, depth, -size, nome.lower())


def _readme_rank_dir(nome: str, size: int) -> tuple:
    # Ranking menor = melhor, apenas por nome/tamanho (uso por diretorio)
    nome_up = nome.upper()
    nome_low = nome.lower()
    prefer_pt = "pt" in nome_low or "br" in nome_low
    prefer_en = "en" in nome_low or "eng" in nome_low
    if prefer_pt:
        lang_rank = 0
    elif prefer_en:
        lang_rank = 1
    else:
        lang_rank = 2
    if nome_up == "README.MD":
        return (lang_rank, 0, -size, nome.lower())
    if nome_up in {"README.RST", "README.TXT"}:
        return (lang_rank, 1, -size, nome.lower())
    if _is_readme(nome):
        return (lang_rank, 2, -size, nome.lower())
    return (lang_rank, 3, -size, nome.lower())


def _hash_arquivo(path: Path) -> str:
    # Hash SHA1 para deduplicar arquivos nao relevantes
    hasher = hashlib.sha1()
    with path.open("rb") as f:
        while True:
            chunk = f.read(8192)
            if not chunk:
                break
            hasher.update(chunk)
    return hasher.hexdigest()


def coletar_arquivos(repo):
    # Coleta de arquivos do repositorio com flags de ignorar
    arquivos = []
    candidatos = []
    for raiz, dirs, files in os.walk(repo):
        # Mantem walk completo; marcamos ignore depois
        for nome in files:
            caminho = Path(raiz) / nome
            rel = os.path.relpath(str(caminho), repo)
            candidatos.append((caminho, rel))

    # Escolha do README principal por diretorio (um por pasta)
    readmes = []
    for caminho, rel in candidatos:
        if _is_readme(caminho.name):
            try:
                size = caminho.stat().st_size
            except Exception:
                size = 0
            readmes.append((rel, caminho.name, size))
    readmes_keep = set()
    if readmes:
        # Agrupa por diretorio e seleciona o melhor README local
        por_dir = {}
        for rel, nome, size in readmes:
            dir_rel = os.path.dirname(rel).replace("\\", "/")
            por_dir.setdefault(dir_rel, []).append((rel, nome, size))
        for dir_rel, itens in por_dir.items():
            keep = sorted(itens, key=lambda x: _readme_rank_dir(x[1], x[2]))[0][0]
            readmes_keep.add(keep)

    # Dedup por hash (apenas para nao relevantes)
    hash_map = {}

    for caminho, rel in candidatos:
        nome = caminho.name
        ext = caminho.suffix.lower()
        rel_norm = rel.replace("\\", "/")
        nome_low = nome.lower()
        # Relevancia por extensao, nome ou prefixos conhecidos
        relevante = (
            nome in NOMES_RELEVANTES
            or ext in EXT_RELEVANTES
            or nome_low.endswith("dockerfile")
            or nome_low.startswith(".env")
        )
        ignore = False
        motivos = []

        # Fora do relevante
        if not relevante:
            ignore = True
            motivos.append("fora_relevantes")

        # Regras de ignorar por nome/exato
        if nome in NOMES_IGNORAR:
            ignore = True
            motivos.append("nome_ignorar")

        # README duplicado (mantem apenas o melhor por diretorio)
        if _is_readme(nome) and readmes_keep and rel not in readmes_keep:
            ignore = True
            motivos.append("readme_duplicado")

        # Regras por extensao e nomes
        if ext in EXT_IGNORAR:
            ignore = True
            motivos.append("ext_ignorar")
        if nome.endswith(".log"):
            ignore = True
            motivos.append("log")
        if nome.endswith(".min.js") or nome.endswith(".min.css"):
            ignore = True
            motivos.append("minificado")
        if "-lock." in nome:
            ignore = True
            motivos.append("lock")

        # Regras por trechos no path (cache, build, etc.)
        for trecho in DIRS_IGNORAR_POR_TRECHO:
            if f"/{trecho}/" in f"/{rel_norm}/":
                ignore = True
                motivos.append(f"dir_trecho:{trecho}")
                break
        for trecho in ARQ_IGNORAR_POR_TRECHO:
            if trecho.lower() == nome.lower():
                ignore = True
                motivos.append(f"arq_trecho:{trecho}")
                break
        for trecho in IGNORAR_DIRS:
            if f"/{trecho}/" in f"/{rel_norm}/":
                ignore = True
                motivos.append(f"dir_ignorar:{trecho}")
                break

        # Limite de tamanho (evita arquivos muito grandes).
        # Notebook (.ipynb) pode ser grande e ainda assim conter contexto essencial.
        try:
            size = caminho.stat().st_size
            max_size = 10 * 1024 * 1024 if ext == ".ipynb" else 300 * 1024
            if size > max_size:
                ignore = True
                motivos.append("tamanho")
        except Exception:
            size = 0

        # Ignorar vazio
        try:
            if size == 0:
                ignore = True
                motivos.append("vazio")
        except Exception:
            pass

        # Heuristicas por conteudo (gerado/minificado)
        if ext != ".ipynb" and _conteudo_indica_gerado(caminho, size):
            ignore = True
            motivos.append("auto_gerado")
        if _indica_bundle(caminho, size):
            ignore = True
            motivos.append("bundle")

        # Dedup por hash (apenas para nao relevantes)
        if not relevante:
            try:
                file_hash = _hash_arquivo(caminho)
                if file_hash in hash_map:
                    ignore = True
                    motivos.append("dedup_hash")
                else:
                    hash_map[file_hash] = rel
            except Exception:
                pass

        # Registro final do arquivo com seus motivos de ignore
        arquivos.append({"path": str(caminho), "rel": rel, "ignore": ignore, "ignore_motivos": motivos})

    return arquivos


# Versao antiga removida: mantemos apenas a coletar_arquivos com ignore
