/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AddOrEditEntityDialog: typeof import('./components/AddOrEditEntityDialog.vue')['default']
    copy: typeof import('./components/NamedEntityRecognitionForm copy.vue')['default']
    EditEntityDialog: typeof import('./components/EditEntityDialog.vue')['default']
    FileForm: typeof import('./components/FileForm.vue')['default']
    Header: typeof import('./components/Header.vue')['default']
    Main: typeof import('./components/Main.vue')['default']
    NamedEntityRecognition: typeof import('./components/NamedEntityRecognition.vue')['default']
    NamedEntityRecognitionForm: typeof import('./components/NamedEntityRecognitionForm.vue')['default']
    NamedEntityRecognitionTable: typeof import('./components/NamedEntityRecognitionTable.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Sidebar: typeof import('./components/Sidebar.vue')['default']
  }
}
